
services:

  frontend:
    image: registry:5000/frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:5173"
    depends_on:
      - read-backend
      - write-backend

  read-backend:
    image: registry:5000/read-backend
    env_file:
      - ./python-read/.env
    ports:
      - "8000:8000"

  write-backend:
    image: registry:5000/write-backend
    env_file:
      - ./python-write/.env
    ports:
      - "8008:8000"

  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 1s
      retries: 3
    volumes:
      - postgres-data:/data

volumes:
  postgres-data:
